// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nebula/ido/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ====== MessageEnableIDO
type MsgEnableIDORequest struct {
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty" yaml:"owner"`
	// Project unique id of each project
	ProjectId            uint64                                   `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty" yaml:"project_id"`
	TokenForDistribution github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=token_for_distribution,json=tokenForDistribution,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"token_for_distribution" yaml:"token_for_distribution"`
	TokenListingPrice    github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,4,rep,name=token_listing_price,json=tokenListingPrice,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"token_listing_price" yaml:"token_listing_price"`
	AllocationLimit      []AllocationLimit                        `protobuf:"bytes,5,rep,name=allocation_limit,json=allocationLimit,proto3" json:"allocation_limit" yaml:"allocation_limit"`
	// Begin time for this ido
	StartTime time.Time `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time" yaml:"start_time"`
}

func (m *MsgEnableIDORequest) Reset()         { *m = MsgEnableIDORequest{} }
func (m *MsgEnableIDORequest) String() string { return proto.CompactTextString(m) }
func (*MsgEnableIDORequest) ProtoMessage()    {}
func (*MsgEnableIDORequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f53dbbfbf1694cb8, []int{0}
}
func (m *MsgEnableIDORequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEnableIDORequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEnableIDORequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEnableIDORequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEnableIDORequest.Merge(m, src)
}
func (m *MsgEnableIDORequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgEnableIDORequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEnableIDORequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEnableIDORequest proto.InternalMessageInfo

func (m *MsgEnableIDORequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgEnableIDORequest) GetProjectId() uint64 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *MsgEnableIDORequest) GetTokenForDistribution() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.TokenForDistribution
	}
	return nil
}

func (m *MsgEnableIDORequest) GetTokenListingPrice() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.TokenListingPrice
	}
	return nil
}

func (m *MsgEnableIDORequest) GetAllocationLimit() []AllocationLimit {
	if m != nil {
		return m.AllocationLimit
	}
	return nil
}

func (m *MsgEnableIDORequest) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

type MsgEnableIDOResponse struct {
}

func (m *MsgEnableIDOResponse) Reset()         { *m = MsgEnableIDOResponse{} }
func (m *MsgEnableIDOResponse) String() string { return proto.CompactTextString(m) }
func (*MsgEnableIDOResponse) ProtoMessage()    {}
func (*MsgEnableIDOResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f53dbbfbf1694cb8, []int{1}
}
func (m *MsgEnableIDOResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEnableIDOResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEnableIDOResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEnableIDOResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEnableIDOResponse.Merge(m, src)
}
func (m *MsgEnableIDOResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgEnableIDOResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEnableIDOResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEnableIDOResponse proto.InternalMessageInfo

type MsgCommitParticipationRequest struct {
	Participant string                                   `protobuf:"bytes,1,opt,name=participant,proto3" json:"participant,omitempty" yaml:"participant"`
	TokenCommit github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=token_commit,json=tokenCommit,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"token_commit" yaml:"token_commit"`
	ProjectId   uint64                                   `protobuf:"varint,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty" yaml:"project_id"`
}

func (m *MsgCommitParticipationRequest) Reset()         { *m = MsgCommitParticipationRequest{} }
func (m *MsgCommitParticipationRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCommitParticipationRequest) ProtoMessage()    {}
func (*MsgCommitParticipationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f53dbbfbf1694cb8, []int{2}
}
func (m *MsgCommitParticipationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCommitParticipationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCommitParticipationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCommitParticipationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCommitParticipationRequest.Merge(m, src)
}
func (m *MsgCommitParticipationRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgCommitParticipationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCommitParticipationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCommitParticipationRequest proto.InternalMessageInfo

func (m *MsgCommitParticipationRequest) GetParticipant() string {
	if m != nil {
		return m.Participant
	}
	return ""
}

func (m *MsgCommitParticipationRequest) GetTokenCommit() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.TokenCommit
	}
	return nil
}

func (m *MsgCommitParticipationRequest) GetProjectId() uint64 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

type MsgCommitParticipationResponse struct {
}

func (m *MsgCommitParticipationResponse) Reset()         { *m = MsgCommitParticipationResponse{} }
func (m *MsgCommitParticipationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCommitParticipationResponse) ProtoMessage()    {}
func (*MsgCommitParticipationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f53dbbfbf1694cb8, []int{3}
}
func (m *MsgCommitParticipationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCommitParticipationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCommitParticipationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCommitParticipationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCommitParticipationResponse.Merge(m, src)
}
func (m *MsgCommitParticipationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCommitParticipationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCommitParticipationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCommitParticipationResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgEnableIDORequest)(nil), "nebula.ido.MsgEnableIDORequest")
	proto.RegisterType((*MsgEnableIDOResponse)(nil), "nebula.ido.MsgEnableIDOResponse")
	proto.RegisterType((*MsgCommitParticipationRequest)(nil), "nebula.ido.MsgCommitParticipationRequest")
	proto.RegisterType((*MsgCommitParticipationResponse)(nil), "nebula.ido.MsgCommitParticipationResponse")
}

func init() { proto.RegisterFile("nebula/ido/tx.proto", fileDescriptor_f53dbbfbf1694cb8) }

var fileDescriptor_f53dbbfbf1694cb8 = []byte{
	// 648 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xb1, 0x4f, 0xdb, 0x4e,
	0x14, 0x8e, 0x09, 0x20, 0xe5, 0x82, 0xf4, 0x83, 0x4b, 0x7e, 0xd4, 0x4d, 0x85, 0x1d, 0x79, 0xa8,
	0x42, 0x25, 0xce, 0x82, 0x76, 0xa8, 0xba, 0x35, 0xd0, 0x56, 0x48, 0x40, 0xa9, 0xd5, 0xa1, 0xea,
	0x12, 0x9d, 0xed, 0xc3, 0xbd, 0x62, 0xfb, 0x5c, 0xdf, 0xa5, 0x85, 0x3f, 0xa0, 0x3b, 0x5b, 0xd5,
	0xb5, 0x63, 0xff, 0x8d, 0x2e, 0x8c, 0x8c, 0x9d, 0x42, 0x05, 0xff, 0x41, 0x96, 0xae, 0x95, 0xef,
	0x2e, 0xc4, 0x20, 0x22, 0x60, 0x8a, 0xef, 0xdd, 0xf7, 0xbe, 0xf7, 0xbd, 0xf7, 0xbe, 0x0b, 0x68,
	0xa4, 0xc4, 0xef, 0xc7, 0xd8, 0xa5, 0x21, 0x73, 0xc5, 0x01, 0xca, 0x72, 0x26, 0x18, 0x04, 0x2a,
	0x88, 0x68, 0xc8, 0x5a, 0xcd, 0x88, 0x45, 0x4c, 0x86, 0xdd, 0xe2, 0x4b, 0x21, 0x5a, 0x56, 0xc0,
	0x78, 0xc2, 0xb8, 0xeb, 0x63, 0x4e, 0xdc, 0xcf, 0xab, 0x3e, 0x11, 0x78, 0xd5, 0x0d, 0x18, 0x4d,
	0xf5, 0x7d, 0xb3, 0x44, 0x4b, 0xc3, 0x51, 0x96, 0x1d, 0x31, 0x16, 0xc5, 0xc4, 0x95, 0x27, 0xbf,
	0xbf, 0xe7, 0x0a, 0x9a, 0x10, 0x2e, 0x70, 0x92, 0x29, 0x80, 0xf3, 0x77, 0x1a, 0x34, 0xb6, 0x79,
	0xf4, 0x22, 0xc5, 0x7e, 0x4c, 0x36, 0x37, 0x5e, 0x7b, 0xe4, 0x53, 0x9f, 0x70, 0x01, 0x1f, 0x82,
	0x19, 0xf6, 0x25, 0x25, 0xb9, 0x69, 0xb4, 0x8d, 0x4e, 0xad, 0x3b, 0x3f, 0x1c, 0xd8, 0x73, 0x87,
	0x38, 0x89, 0x9f, 0x39, 0x32, 0xec, 0x78, 0xea, 0x1a, 0x3e, 0x01, 0x20, 0xcb, 0xd9, 0x47, 0x12,
	0x88, 0x1e, 0x0d, 0xcd, 0xa9, 0xb6, 0xd1, 0x99, 0xee, 0xfe, 0x3f, 0x1c, 0xd8, 0x0b, 0x0a, 0x3c,
	0xbe, 0x73, 0xbc, 0x9a, 0x3e, 0x6c, 0x86, 0xf0, 0x87, 0x01, 0x16, 0x05, 0xdb, 0x27, 0x69, 0x6f,
	0x8f, 0xe5, 0xbd, 0x90, 0x72, 0x91, 0x53, 0xbf, 0x2f, 0x28, 0x4b, 0xcd, 0x6a, 0xbb, 0xda, 0xa9,
	0xaf, 0xdd, 0x47, 0xaa, 0x5d, 0x54, 0xb4, 0x8b, 0x74, 0xbb, 0x68, 0x9d, 0xd1, 0xb4, 0xfb, 0xe6,
	0x78, 0x60, 0x57, 0x86, 0x03, 0x7b, 0x49, 0x55, 0xb8, 0x9e, 0xc6, 0xf9, 0x79, 0x6a, 0x77, 0x22,
	0x2a, 0x3e, 0xf4, 0x7d, 0x14, 0xb0, 0xc4, 0xd5, 0xc3, 0x53, 0x3f, 0x2b, 0x3c, 0xdc, 0x77, 0xc5,
	0x61, 0x46, 0xb8, 0x64, 0xe4, 0x5e, 0x53, 0x92, 0xbc, 0x64, 0xf9, 0x46, 0x89, 0x02, 0x7e, 0x37,
	0x40, 0x43, 0xb1, 0xc7, 0x94, 0x0b, 0x9a, 0x46, 0xbd, 0x2c, 0xa7, 0x01, 0x31, 0xa7, 0x6f, 0x52,
	0xb8, 0xa3, 0x15, 0xb6, 0xca, 0x0a, 0x2f, 0x71, 0xdc, 0x4d, 0xde, 0x82, 0x64, 0xd8, 0x52, 0x04,
	0xbb, 0x45, 0x3e, 0x8c, 0xc0, 0x3c, 0x8e, 0x63, 0x16, 0xe0, 0x42, 0x69, 0x2f, 0xa6, 0x09, 0x15,
	0xe6, 0x8c, 0xd4, 0xf5, 0x00, 0x8d, 0xad, 0x84, 0x9e, 0x5f, 0x60, 0xb6, 0x0a, 0x48, 0xd7, 0xd6,
	0xca, 0xee, 0x29, 0x65, 0x57, 0x29, 0x1c, 0xef, 0x3f, 0x7c, 0x39, 0x03, 0xbe, 0x03, 0x80, 0x0b,
	0x9c, 0x8b, 0x5e, 0x61, 0x1c, 0x73, 0xb6, 0x6d, 0x74, 0xea, 0x6b, 0x2d, 0xa4, 0x5c, 0x85, 0x46,
	0xae, 0x42, 0x6f, 0x47, 0xae, 0xea, 0x2e, 0xe9, 0x0a, 0x7a, 0xff, 0xe3, 0x5c, 0xe7, 0xe8, 0xd4,
	0x36, 0xbc, 0x9a, 0x0c, 0x14, 0x70, 0x67, 0x11, 0x34, 0x2f, 0x1b, 0x8f, 0x67, 0x2c, 0xe5, 0xc4,
	0xf9, 0x36, 0x05, 0x96, 0xb6, 0x79, 0xb4, 0xce, 0x92, 0x84, 0x8a, 0x5d, 0x9c, 0x0b, 0x1a, 0xd0,
	0x4c, 0x2a, 0x1a, 0x79, 0xf3, 0x29, 0xa8, 0x67, 0xa3, 0x78, 0x2a, 0xb4, 0x43, 0x17, 0x87, 0x03,
	0x1b, 0x6a, 0xd3, 0x8d, 0x2f, 0x1d, 0xaf, 0x0c, 0x85, 0x5f, 0x0d, 0x30, 0xa7, 0xd6, 0x11, 0x48,
	0x7a, 0x73, 0xea, 0xa6, 0x5d, 0xbe, 0xd2, 0xfd, 0x34, 0xca, 0xbb, 0x54, 0xc9, 0x77, 0x5b, 0x62,
	0x5d, 0xa6, 0xaa, 0xae, 0xae, 0xbc, 0x9a, 0xea, 0xed, 0x5e, 0x8d, 0xd3, 0x06, 0xd6, 0xa4, 0xc1,
	0xa8, 0xd9, 0xad, 0xfd, 0x32, 0x40, 0x75, 0x9b, 0x47, 0x70, 0x07, 0xd4, 0x2e, 0x06, 0x0b, 0xed,
	0xb2, 0x23, 0xae, 0x79, 0xeb, 0xad, 0xf6, 0x64, 0x80, 0xe2, 0x85, 0x31, 0x68, 0x5c, 0x53, 0x16,
	0x2e, 0x5f, 0x49, 0x9c, 0xbc, 0xb3, 0xd6, 0xa3, 0xdb, 0x40, 0x55, 0xb5, 0xee, 0xfa, 0xf1, 0x99,
	0x65, 0x9c, 0x9c, 0x59, 0xc6, 0x9f, 0x33, 0xcb, 0x38, 0x3a, 0xb7, 0x2a, 0x27, 0xe7, 0x56, 0xe5,
	0xf7, 0xb9, 0x55, 0x79, 0xbf, 0x5c, 0x1a, 0xb7, 0xe2, 0x5b, 0x89, 0xb1, 0xcf, 0xf5, 0xb7, 0x7b,
	0xa0, 0xfe, 0x54, 0x8b, 0xa9, 0xfb, 0xb3, 0xd2, 0x9c, 0x8f, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x10, 0x28, 0x69, 0x15, 0x6f, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	EnableIDO(ctx context.Context, in *MsgEnableIDORequest, opts ...grpc.CallOption) (*MsgEnableIDOResponse, error)
	CommitParticipation(ctx context.Context, in *MsgCommitParticipationRequest, opts ...grpc.CallOption) (*MsgCommitParticipationResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) EnableIDO(ctx context.Context, in *MsgEnableIDORequest, opts ...grpc.CallOption) (*MsgEnableIDOResponse, error) {
	out := new(MsgEnableIDOResponse)
	err := c.cc.Invoke(ctx, "/nebula.ido.Msg/EnableIDO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CommitParticipation(ctx context.Context, in *MsgCommitParticipationRequest, opts ...grpc.CallOption) (*MsgCommitParticipationResponse, error) {
	out := new(MsgCommitParticipationResponse)
	err := c.cc.Invoke(ctx, "/nebula.ido.Msg/CommitParticipation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	EnableIDO(context.Context, *MsgEnableIDORequest) (*MsgEnableIDOResponse, error)
	CommitParticipation(context.Context, *MsgCommitParticipationRequest) (*MsgCommitParticipationResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) EnableIDO(ctx context.Context, req *MsgEnableIDORequest) (*MsgEnableIDOResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableIDO not implemented")
}
func (*UnimplementedMsgServer) CommitParticipation(ctx context.Context, req *MsgCommitParticipationRequest) (*MsgCommitParticipationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitParticipation not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_EnableIDO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgEnableIDORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).EnableIDO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nebula.ido.Msg/EnableIDO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).EnableIDO(ctx, req.(*MsgEnableIDORequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CommitParticipation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCommitParticipationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CommitParticipation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nebula.ido.Msg/CommitParticipation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CommitParticipation(ctx, req.(*MsgCommitParticipationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nebula.ido.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnableIDO",
			Handler:    _Msg_EnableIDO_Handler,
		},
		{
			MethodName: "CommitParticipation",
			Handler:    _Msg_CommitParticipation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nebula/ido/tx.proto",
}

func (m *MsgEnableIDORequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEnableIDORequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEnableIDORequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintTx(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x32
	if len(m.AllocationLimit) > 0 {
		for iNdEx := len(m.AllocationLimit) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AllocationLimit[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.TokenListingPrice) > 0 {
		for iNdEx := len(m.TokenListingPrice) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TokenListingPrice[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.TokenForDistribution) > 0 {
		for iNdEx := len(m.TokenForDistribution) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TokenForDistribution[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.ProjectId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ProjectId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgEnableIDOResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEnableIDOResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEnableIDOResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCommitParticipationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCommitParticipationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCommitParticipationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProjectId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ProjectId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.TokenCommit) > 0 {
		for iNdEx := len(m.TokenCommit) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TokenCommit[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Participant) > 0 {
		i -= len(m.Participant)
		copy(dAtA[i:], m.Participant)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Participant)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCommitParticipationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCommitParticipationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCommitParticipationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgEnableIDORequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ProjectId != 0 {
		n += 1 + sovTx(uint64(m.ProjectId))
	}
	if len(m.TokenForDistribution) > 0 {
		for _, e := range m.TokenForDistribution {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.TokenListingPrice) > 0 {
		for _, e := range m.TokenListingPrice {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.AllocationLimit) > 0 {
		for _, e := range m.AllocationLimit {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgEnableIDOResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCommitParticipationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Participant)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.TokenCommit) > 0 {
		for _, e := range m.TokenCommit {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.ProjectId != 0 {
		n += 1 + sovTx(uint64(m.ProjectId))
	}
	return n
}

func (m *MsgCommitParticipationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgEnableIDORequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEnableIDORequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEnableIDORequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectId", wireType)
			}
			m.ProjectId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProjectId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenForDistribution", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenForDistribution = append(m.TokenForDistribution, types.Coin{})
			if err := m.TokenForDistribution[len(m.TokenForDistribution)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenListingPrice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenListingPrice = append(m.TokenListingPrice, types.Coin{})
			if err := m.TokenListingPrice[len(m.TokenListingPrice)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllocationLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllocationLimit = append(m.AllocationLimit, AllocationLimit{})
			if err := m.AllocationLimit[len(m.AllocationLimit)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgEnableIDOResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEnableIDOResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEnableIDOResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCommitParticipationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCommitParticipationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCommitParticipationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Participant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenCommit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenCommit = append(m.TokenCommit, types.Coin{})
			if err := m.TokenCommit[len(m.TokenCommit)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectId", wireType)
			}
			m.ProjectId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProjectId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCommitParticipationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCommitParticipationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCommitParticipationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
